import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class WordleWordsService {
  words = [
    'CAGAR',
    'NDEAH',
    'JODER',
    'BURRO',
    'BONDI',
    'JAVIE',
    'CHAFI',
    'PIOLA',
    'FLACA',
    'FACHO',
    'CURDA',
    'FACHA',
    'TANGO',
    'BARDO',
    'CAPOS',
    'CUCHA',
    'TURRO',
    'GUITA',
    'MANGO',
    'MINAS',
    'MINGA',
    'ÑOQUI',
    'PIBES',
    'PUCHO',
    'LUCAS',
    'GANGA',
    'TONGO',
    'ZAMBA',
    'MAMBO',
    'AFANO',
    'FIACA',
    'GROSO',
    'GUITA',
    'MORFI',
    'PIBES',
    'TUJES',
    'ASADO',
    'ORSAI',
    'PUNGA',
    'GAMBA',
    'UPITE',
    'BOCHA',
    'SKERE',
    'TRUCO',
    'CHOTO',
    'ZAPAN',
    'CHIVO',
    'GORRA',
    'GROSA',
    'GUASO',
    'ZAFAR',
    'PINTA',
    'LORCA',
    'YERBA',
    'GARRA',
    'FULBO',
    'PLOMO',
    'BAJON',
    'NAPIA',
    'CROTO',
    'CRACK',
    'MUFAR',
    'FORRO',
    'AFANO',
    'BOTON',
    'PINGO',
  ];
  rightGuessString = this.words[Math.floor(Math.random() * this.words.length)];
  constructor() {}
}
